name: Hello DevOps

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print hello
        run: echo "Hello DevOps! A kód frissült!"
